### ISSUE TITLE
Allow User to choose Audio Output device

### ISSUE THREAD

**Issue by lawrab** [dennis/slipstream#34]
As a streamer, I need to change the audio output device from Default to a specific device so that I can decide if audio should be played on stream or not.

I would like the ability to control this from the scripts as it could depend on the purpose of the script.

**!say** hello world -> audio sent to device mixed into stream output
**!saysecret** do you want some coffee, nod if you do -> played to headset only and not on stream output.

**Comment by dennis** [comment]
Me brainstorming a bit:

1) You create a AudioPlugin per device you wish to use. 
2) Play/Say command events needs a target, so the correct plugin will act on it. 
3) AudioPlugin should use the ID as name for workerName (so they run in different threads)
4) To select what device should be used, Let `AudioPlugin` use "default" device, until you tell them otherwise (A `AudioCommandChangeDevice`). This is easiest to do and is probably what we should start with. Perhaps also create a `AudioCommandShowDevices`, so you know what values to use as device.
5) In Lua: We need another parameter to for `audio:say` and `audio:play` to decide on which device to use. We could inject some Lua code to make the syntax a bit more pleasant (like having two commands as you suggest).

**Comment by dennis** [comment]
Implemented as of https://github.com/dennis/slipstream/pull/42
